---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	fetch_top_news(fetch_top_news)
	fetch_related_news(fetch_related_news)
	generate_report(generate_report)
	run_tts(run_tts)
	__end__([<p>__end__</p>]):::last
	__start__ --> fetch_top_news;
	fetch_related_news --> generate_report;
	fetch_top_news --> fetch_related_news;
	generate_report --> run_tts;
	run_tts --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
